### PR TITLE
Update centos7.rst

### PR DESCRIPTION
**Pull request by nwildner**
Composer hash is wrong leading to a "Installer corrupt" error plus, php package is missing on CentOS package installation guide.

### CODE REVIEW

**Comment by nwildner** [comment]
Actually, there is more on this guide that is wrong. It will not work with php-5.4, the default version that is on CentOS repos

```
[root@syspass syspass]# php composer.phar install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ~7.0 || ~7.1 || ~7.2 but your HHVM version does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/annotations v1.4.0 -> satisfiable by doctrine/annotations[v1.4.0].
    - doctrine/annotations v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/cache v1.6.2 -> satisfiable by doctrine/cache[v1.6.2].
    - doctrine/cache v1.6.2 requires php ~5.5|~7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/collections v1.4.0 -> satisfiable by doctrine/collections[v1.4.0].
    - doctrine/collections v1.4.0 requires php ^5.6 || ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 5
    - Installation request for doctrine/common v2.7.3 -> satisfiable by doctrine/common[v2.7.3].
    - doctrine/common v2.7.3 requires php ~5.6|~7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 6
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 7
    - Installation request for guzzlehttp/guzzle 6.3.3 -> satisfiable by guzzlehttp/guzzle[6.3.3].
    - guzzlehttp/guzzle 6.3.3 requires php >=5.5 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 8
    - Installation request for guzzlehttp/promises v1.3.1 -> satisfiable by guzzlehttp/promises[v1.3.1].
    - guzzlehttp/promises v1.3.1 requires php >=5.5.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 9
    - Installation request for nikic/php-parser v4.1.1 -> satisfiable by nikic/php-parser[v4.1.1].
    - nikic/php-parser v4.1.1 requires php >=7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 10
    - Installation request for paragonie/random_compat v9.99.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 11
    - Installation request for php-di/php-di 6.0.5 -> satisfiable by php-di/php-di[6.0.5].
    - php-di/php-di 6.0.5 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 12
    - Installation request for phpmailer/phpmailer v6.0.6 -> satisfiable by phpmailer/phpmailer[v6.0.6].
    - phpmailer/phpmailer v6.0.6 requires php >=5.5.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 13
    - Installation request for symfony/debug v3.4.21 -> satisfiable by symfony/debug[v3.4.21].
    - symfony/debug v3.4.21 requires php ^5.5.9|>=7.0.8 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 14
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.4.16) does not satisfy that requirement.
    - defuse/php-encryption v2.2.1 requires paragonie/random_compat >= 2 -> satisfiable by paragonie/random_compat[v9.99.99].
    - Installation request for defuse/php-encryption v2.2.1 -> satisfiable by defuse/php-encryption[v2.2.1].
```

Versions:

```
[root@syspass ~]# rpm -qa | grep php
php-5.4.16-46.el7.x86_64
php-mbstring-5.4.16-46.el7.x86_64
php-cli-5.4.16-46.el7.x86_64
php-mysqlnd-5.4.16-46.el7.x86_64
php-common-5.4.16-46.el7.x86_64
php-gd-5.4.16-46.el7.x86_64
php-xml-5.4.16-46.el7.x86_64
php-pdo-5.4.16-46.el7.x86_64
php-mcrypt-5.4.16-7.el7.x86_64
php-ldap-5.4.16-46.el7.x86_64
```

Maybe using the [Webtatic](https://webtatic.com/) repo could be a solution since they provide php versions 7.1 and 7.2 to EL7 based distros.

**Comment by nwildner** [comment]
Well, seems the author is not interested in fixes. Closing it...

**Comment by nuxsmin** [comment]
@nwildner so sorry, I missed your PR since I've been focused on solving many issues and preparing for v3.1 release.

I'll merge this PR.

Thanks for your contribution and apologize for the delay. 

Kind regards

**Comment by nuxsmin** [comment]
@nwildner anyway, whenever you have an unanswered issue or PR, please feel free to ping me back...

**Pull request closed without merging**
